/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { AboutTheProject } from '../components/AboutTheProject';
import { AppLayout } from '../components/layout/AppLayout';
import { Styles } from '../styles/styles';
import { NavBar } from '../components/Navbar';
import { LandingPage } from '../components/LandingPage';

const Home: NextPage = () => {
  return (
    <AppLayout>
      <>
        <Head>
          <title>Community garden</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icons/sapling.svg" />
        </Head>
        <div>
          <NavBar />
        </div>

        <div
          style={{
            backgroundColor: Styles.lightGreenBackgroundColor,
            height: '100vh',
          }}
        >
          <LandingPage />
        </div>

        <div className="AboutTheProjectSection">
          <AboutTheProject />
        </div>
      </>
    </AppLayout>
  );
};

export default Home;
